Wes review 2024-07-15
intarchboard/workshop-nemops pull request #1
Opened 2024-07-15 20:38 UTC by hardaker

2024-07-16 03:29 UTC, dhruvdhody requested changes
Can we break this into 2 sentences -

Collaboratively sketch new requirements for future network management operations with the industry, network operators, and protocol engineers. Develop a plan of action and recommendations for the IETF.

2024-07-16 03:32 UTC, dhruvdhody commented
Thanks Wes! Except for that one very minor change request, it is ready to merge. Thanks!

2024-07-16 06:19 UTC, boucadair requested changes
Thanks for the edits.

2024-07-16 06:19 UTC, boucadair commented on IAB-Workshop.md
> +The mailing list nemops-interest@iab.org will be used for outreach events at other conferences, general announcements, and related discussions before (and after) the workshop is held at the end of 20
```suggestion
The mailing list nemops-interest@iab.org will be used for outreach events at other conferences, general announcements, and related discussions before (and after) the workshop.
```

2024-07-16 06:19 UTC, boucadair commented on IAB-Workshop.md
> +- Sketch new requirements for future network management operations in a collaborative manner with the industry, network operators and protocol engineers and develop a plan of action and recommendatio
```suggestion
- Sketch new requirements for future network management operations in a collaborative manner with the industry, network operators, and protocol engineers.

 - Develop a plan of action and recommendations for the IETF.
```

2024-07-16 06:19 UTC, boucadair commented on IAB-Workshop.md
> +The first focus of the IAB NEMOPS workshop will be to assess the recommendations and requirements documented in RFC3535 in terms of specification completeness, deployment and utilization. Also, this
```suggestion
The first focus of the IAB NEMOPS workshop will be to assess the requirements documented in RFC3535 in terms of specification completeness, deployment, and utilization. Also, this workshop will assess to what extent the RFC3535 recommendations were driving network management efforts within the IETF and influencing other Standards Development Organizations' (SDOs) activities. 
```

2024-07-16 06:19 UTC, boucadair commented on IAB-Workshop.md
> +The first focus of the IAB NEMOPS workshop will be to assess the recommendations and requirements documented in RFC3535 in terms of specification completeness, deployment and utilization. Also, this
3535 reco are IETF-centric and are mentioned in the sentence right after.

2024-07-16 06:19 UTC, boucadair commented on IAB-Workshop.md
> +- Sketch new requirements for future network management operations in a collaborative manner with the industry, network operators and protocol engineers and develop a plan of action and recommendatio
Split the sentence for better readability

2024-07-16 06:19 UTC, boucadair commented on IAB-Workshop.md
> +- What recommendations and requirements from RFC3535 have received either or both little implementation or deployment?
```suggestion
- What requirements from RFC3535 have received either or both little implementation or deployment?
```

2024-07-16 06:19 UTC, boucadair commented on IAB-Workshop.md
> +Recommendations that may come out of this effort should be helpful to the standardization development organizations including the IETF and the IRTF, as well as the global industry's implementers, ope
```suggestion
Recommendations that may come out of this effort should be helpful to the global industry including the IETF, the IRTF, implementers, operational groups, and other entities.
```

2024-07-16 15:35 UTC, hardaker commented on IAB-Workshop.md
> +The first focus of the IAB NEMOPS workshop will be to assess the recommendations and requirements documented in RFC3535 in terms of specification completeness, deployment and utilization. Also, this
Those are two different notions in the sentences though.  So, IMHO, they should both say "recommendations and requirements" as the first sentence talks about compleness, deployment and utilization of both, and the second is about whether or not both have affected other SDOs or not.

2024-07-16 15:36 UTC, hardaker commented on IAB-Workshop.md
> +- What recommendations and requirements from RFC3535 have received either or both little implementation or deployment?
disagree with this -- 3535 has both recommendations and requirements and I was trying to make it very clear that both will be discussed/analyzed/etc.  It's overly verbose, but such is the way of the IETF (IMHO).

2024-07-16 15:37 UTC, hardaker commented on IAB-Workshop.md
> +Recommendations that may come out of this effort should be helpful to the standardization development organizations including the IETF and the IRTF, as well as the global industry's implementers, ope
So we don't intend to create advice that might be helpful to SDOs?

2024-07-17 07:38 UTC, boucadair commented on IAB-Workshop.md
> +The first focus of the IAB NEMOPS workshop will be to assess the recommendations and requirements documented in RFC3535 in terms of specification completeness, deployment and utilization. Also, this
I'm having troubles to see what "deployment, and utilization" is about for a set of reco that were about creating WGs, dedicate resources, and some other IETF matters.

2024-07-17 07:46 UTC, boucadair commented on IAB-Workshop.md
> +Recommendations that may come out of this effort should be helpful to the standardization development organizations including the IETF and the IRTF, as well as the global industry's implementers, ope
other "SDOs" fall under "other entities".  

Actually, the initial wording (and thus what this change tries to revert back) is to put the emphasis on the global industry approach not separating SDOs vs rest of the ecosystem.

2024-07-17 07:58 UTC, boucadair commented on IAB-Workshop.md
> +- What recommendations and requirements from RFC3535 have received either or both little implementation or deployment?
Fully agree that both need to be discussed/analyzed/etc. 

My concern is related to mixing these two and talk about "deployment, etc." when referring to considerations related to IETF resources (3535 reco). Please note that we do already have the following in the preamble: 

"Assess to what extent the RFC3535 recommendations were driving network management efforts within the IETF"

2024-07-17 14:52 UTC, billwuqin commented on IAB-Workshop.md
> +The first focus of the IAB NEMOPS workshop will be to assess the recommendations and requirements documented in RFC3535 in terms of specification completeness, deployment and utilization. Also, this
Have this issue resolved? My understanding on utilization is about whether specific part of recommendation or requirements have been quoted or referenced by some standard work in other SDOs.

2024-07-17 14:54 UTC, billwuqin commented on IAB-Workshop.md
> +Recommendations that may come out of this effort should be helpful to the standardization development organizations including the IETF and the IRTF, as well as the global industry's implementers, ope
see SDOs as part of global industry is new to me but fine, traditionally SDOs focus on developing standard work while industry consortium is responsible for get it deployed or implemented.

2024-07-17 23:23 UTC, hardaker commented on IAB-Workshop.md
> +- What recommendations and requirements from RFC3535 have received either or both little implementation or deployment?
I think we want to do both though -- we want to see what was done within the IETF, and whether the results of anything done inside the ietf were used outside.  IE, is netconf getting used?  is SNMP getting sunsetted?  Is everyone just switching to REST?  What's the state of the world, and is it diverging from IETF specs and what can the IETF do (now) to improve things.  It involves both the past, the effect internal and the effect externally, right?

2024-07-22 21:00 UTC, bclaise commented on IAB-Workshop.md
> +Recommendations that may come out of this effort should be helpful to the standardization development organizations including the IETF and the IRTF, as well as the global industry's implementers, ope
So we don't intend to create advice that might be helpful to SDOs? => yes we do, but you will see that, getting in the higher levels of OPS architecture, more and more opensource will be involved ... where the IETF is the facilitator. Therefore, I agree with Med's proposal

2024-07-22 22:29 UTC, merged

2024-07-23 15:28 UTC, hardaker commented
for any outstanding changes, since this is now merged, I'd create separate pull requests for them